import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { DollarSign, TrendingUp, Handshake, Zap } from "lucide-react";
const GameAcquisitionSection = () => {
  const features = [{
    icon: DollarSign,
    title: "Full Game Acquisition",
    description: "We purchase your Roblox game outright, offering a competitive upfront payment."
  }, {
    icon: TrendingUp,
    title: "Expert Development & Marketing",
    description: "Our experienced team takes over development, marketing, and ongoing optimization, ensuring your game thrives in the long run."
  }, {
    icon: Handshake,
    title: "Revenue Sharing",
    description: "You will benefit from continued revenue generated by your game through a transparent revenue-sharing model."
  }, {
    icon: Zap,
    title: "Hassle-Free Transition",
    description: "Sit back and relax! We handle everything from the sale to future management, allowing you to focus on your next big idea."
  }];
  return <section id="acquisitions" className="bg-muted py-20">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold text-foreground mb-6">
            Game Acquisition
          </h2>
          
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-12">
          {features.map((feature, index) => <Card key={index} className="p-6 hover:shadow-lg transition-shadow duration-300">
              <div className="flex items-start space-x-4">
                <div className="bg-gaming-blue/10 p-3 rounded-2xl">
                  <feature.icon className="w-6 h-6 text-gaming-blue" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-foreground mb-2">
                    {feature.title}
                  </h3>
                  <p className="text-muted-foreground leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </div>
            </Card>)}
        </div>

        <div className="text-center">
          <Button variant="gaming" size="lg" asChild>
            <a href="#contact" className="flex items-center gap-2">
              🤝 Let's get started
            </a>
          </Button>
          <p className="text-sm text-muted-foreground mt-4">
            Send us a message with your game link and metrics
          </p>
        </div>
      </div>
    </section>;
};
export default GameAcquisitionSection;